name: 1cp3workerlatest-mgmt
kubernetesVersion: 1.33
provider: libvirt
headless: true
controlPlaneNodes: 1
providers:
  libvirt:
    controlPlaneNode:
      cpu: 3
      memory: 10000000K
      storage: 30G
